---
title: "CTC Analysis"
author: "Nikhil Kalra"
format:
  html:
    toc: true
    number-sections: true
  docx:
    #reference-doc: "PhD-thesis_NK_2024-11"
    toc: true
  pdf:
    toc: true
editor: visual
execute:
  echo: true
  warning: false
  output: asis
fig-dpi: 300
fig-width: 6
fig-height: 8
tbl-cap-location: top
---

# CTCproject

CTCproject is focused on statistical considerations for enumeration of Circulating Tumor Cells (CTCs) released during diagnostic biopsies in breast cancer patients.

CTCs represent tumor cells that have successfully detached from the primary lesion or metastatic site(s) and entered the bloodstream and currently a major focus of cancer research due to their vital role in metastatic process. It is estimated that a tumor releases thousands of tumor cells into circulation every day. Very few of them are actually able to survive and colonize distant organs to establish secondary tumors. Majority of them perish soon after they enter the bloostream due to different mechanisms, such as shear stress, anoikis (apoptosis due to dissociation from neighbouring cells and Extracellular matrix), attack from body's immune response, nutrient deprivation and metabolic changes.

Their detection and enumeration in blood is a technical challenge due to their rarity in blood (1 CTC every 10\^6-10\^8 normal cells) and heterogeneity (lack of universal CTC markers). Many enrichment techniques have been commercialised and in developmental phase for their isolation and enumeration.

In CTCproject, I used two different techniques to detect and count them in peripheral blood using liquid biopsy. I'm specifically looking for their increased release in blood due to tissue injury during breast biopsies. Since it is an early disease setting, baseline CTC counts are expected to be very low. Moreover detecting the increase of CTCs due to biopsies is challenging.

## Included Scripts

All analysis scripts are available under `Rscripts/`:

1.  Loading Packages
2.  Importing Raw Data
3.  Filtering Complete Cases
4.  Pivoting Raw Data (Wide and Long)
5.  Clinicopathological Data Table 1
6.  Bland-Altman Analysis
7.  CTC Counts Table 2 and Table 3
8.  CTC Positive Cases
9.  Recruitment Plot
10. Waterfall Plot
11. CTC Distribution Plot
12. CTC Dynamics Plot
13. Univariable Analysis
14. Binomial Regression / Poisson Model
15. Zero-Inflated Regression Model
16. Regression Plot
17. CNA Plots

## Rendering and Reproducibility

To render the entire project or specific scripts, use:

\`\`\`bash \
quarto render
